### ISSUE TITLE
Multiple layout issues with Firefox

### ISSUE THREAD

**Issue by JasonHK** [simple-login/browser-extension#100]
1. The button to create an alias was not reachable.
2. Blank space on the bottom that was not utilised.

These issues occurred when the extension was opened from the sub-menu. Please see the attached screenshot for more details.

![20210901-00002](https://user-images.githubusercontent.com/4410086/131971284-9bb135f6-5618-40a1-b1f3-03643f8dd7e9.jpg)

**Comment by nguyenkims** [comment]
@JasonHK Do you know if you have the latest Firefox version? I just tested on my Firefox and don't see this layout issue.

**Comment by JasonHK** [comment]
> @JasonHK Do you know if you have the latest Firefox version? I just tested on my Firefox and don't see this layout issue.

@nguyenkims The issue occurs when the pop-up was opened from the overflow menu, and the create button become unreachable when display scaling was over 100%.

P.S. Sorry for the late reply
