### ISSUE TITLE
Please upgrade the repo & manifest to Ver 3.

### ISSUE THREAD

**Issue by thanosforking** [simple-login/browser-extension#133]
HI Team & Community, 
First & foremost, thanks for the amazing product. We recently tried self-hosting this app fortunately it went well without any hiccups but when it comes to chrome extension we have faced some issues due to manifest version 2. Chrome urges to follow Ver 3 guidelines. 

So can we expect this repository to be updated to Ver 3 by any chance. Im sure people out there must have gone through this issue. 
Hope you consider.

Thanks in advance.

**Comment by nguyenkims** [comment]
@thanosforking we do have a plan to upgrade to manifest v3. Unfortunately this new manifest version isn't supported (yet) by all browsers and as we use a common code base for all browsers, we can't just make exception for Chrome.

I'd suggest to use another Chromium browser in the meantime and wait for the manifest v3 to be supported in SimpleLogin. I don't expect for this to come soon though as a)manifest v3 requires a lot of changes b)the new manifest version doesn't seem to be stable yet.

You can also just install our chrome extension and update the api URL to your self hosted server.
