### ISSUE TITLE
Issue with Brave Browser!

### ISSUE THREAD

**Issue by gcpmusic** [simple-login/browser-extension#182]
Basically every time I open Brave, the simple-login extension is corrupted and I have to keep repaire it.  With Firefox works just fine.

Any solution?

Thanks in advance.

OSX Mojave - INTEL

**Comment by nguyenkims** [comment]
@gcpmusic can you send a screenshot of the error please? I just tested with Brave and SL extension seems to be working.

**Comment by nguyenkims** [comment]
@gcpmusic I have tried to reproduce the issue by installing SL on Brave but don't see any error, maybe you can try to uninstall and reinstall the extension?

**Comment by gcpmusic** [comment]
Thank you nguyenkims, I did follow your advise and re-install it again but no eval. As before, no errors and works fine but every time I open Brave I have to repair it again.

<img width="821" alt="Screenshot 2023-04-06 at 10 18 59" src="https://user-images.githubusercontent.com/32528176/230320376-3d33b08f-c9ca-40a6-a2b5-8ffde4327723.png">

**Comment by nguyenkims** [comment]
@gcpmusic I wonder if maybe upgrading Brave can help? Do you see a more detailed error when clicking on "Details" button?

**Comment by gcpmusic** [comment]
Well I am using the extension for a while and Brave was update at least  4-5 times, included the last one yesterday.

Unfortunately there are any detailed error when clicking on "Details" button as the 2nd screenshot of my first post.

Brave is a little devil browser, and I dont trust it as all chromium family, and I have to block many unwanted obscure connection that Brave do on start up such :
*.brave.com
*.home
*.station
*.clearurls.xyz
api.rewards.brave.com
pcdn.brave.com
rewards.brave.com
variations.brave.com
*.bravesoftware.com
laptop-updates.brave.com
componentupdater.brave.com
redirector.brave.com
*.https-rulesets.org
crlsets.brave.com
tatic1.brave.com
*.accounts.binance.com
*.api.infura.io
mainnet-infura.brave.com
min-api.cryptocompare.com
static.brave.com
static1.brave.com
*.no-thanks.invalid

I dont know if this blocks can interfere with the extension, however all the other works just fine so I dont thing so.

Anyway, fortunately I need simple-login once in a while just to create some Proton email alias so is not a big deal for me to repair it just when I ned it or use Firefox where works fine.

Many thanks for developing such useful extension.

**Comment by gcpmusic** [comment]
Thanks.

**Comment by gcpmusic** [comment]
Hello,
I re-opend this issue as I did found more related errors in Brave console which hope could help to solve this issue.

Thanks

<img width="1144" alt="Screenshot 2023-04-29 at 14 43 15" src="https://user-images.githubusercontent.com/32528176/235303164-fcccf74b-1996-49ef-94d4-e6320d30473e.png">

**Comment by nguyenkims** [comment]
@gcpmusic the logs you have aren't from SimpleLogin but rather logs from the brave://extensions page.

**Comment by gcpmusic** [comment]
Hello nguyenkims,

it is from the Brave console and is related to the simpleLogin extension.

Thanks

**Comment by gcpmusic** [comment]
Hi nguyenkims,

just to let you know that from a couple of days, SL is working as expected and doesnt get corrupted anymore in Brave.

I dont know why. May be SL as been updated or the last Brave update sort it out anyway.

Thank you for your support again.
