### ISSUE TITLE
Icon shows with white background in browser toolbar

### ISSUE THREAD

**Issue by unikitty37** [simple-login/browser-extension#5]
The icon in the browser toolbar shows with a white background even when a dark toolbar is in use:

![image](https://user-images.githubusercontent.com/139183/78130374-20190c80-7411-11ea-89f4-5925af9622c6.png)

(I'm a bit confused as how this is happening, as the icons have transparent backgrounds!)

While the envelope and the inside of the shield should be white, having the actual background would be transparent would be much better — having it appear as a white square is rather annoying as it drags the attention to the toolbar unnecessarily. You can see the difference compared to the other icons — SimpleLogin appears to be shouting for attention.

(This is using Vivaldi 2.11.1811.49 on Mac OS X 10.14.6 (18G3020), in case it matters)

The new icon's much better than the old one, though 👍

**Comment by nguyenkims** [comment]
@unikitty37 sorry for the late reply! Now the icon is more compatible with both light theme and dark theme as you can see in the below screenshots :)

![image](https://user-images.githubusercontent.com/3167780/87705460-31a6da00-c79e-11ea-84fd-bcf5d6b7819a.png)

![image](https://user-images.githubusercontent.com/3167780/87705491-408d8c80-c79e-11ea-89b2-d55429a409bc.png)

**Comment by unikitty37** [comment]
Thanks 👍
