### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by fabianski7** [simple-login/browser-extension#51]
Please, when releasing new versions, publish the changelog with the changes made. 
I was using an old version and when upgrading to the latest one a new permission was requested, I came here to find out what had changed but there is no information in the most recent releases. I had to look through the recent commits.

**Comment by nguyenkims** [comment]
@fabianski7 I don't know the github changelog, we update this CHANGELOG file for every new version https://github.com/simple-login/browser-extension/blob/master/CHANGELOG

To avoid compatibility issue, I'd suggest you either:
- build and install your own Firefox add-on. The build is actually not complex and only depends on NodeJS. The instructions is in the README.
- find a way to disable automatic upgrade in Firefox. This way you can control the version you want to run.

The release schedule of the browser extension doesn't follow the server Docker image so in the future, there might be incompatibility between those.

**Comment by fabianski7** [comment]
I think you got it wrong. 
I didn't have any compatibility problems, I just would like to receive the changelog of the new versions by email.
To do that, when a new version is released here on github, you should include the changelog with it. 

Like this:
https://github.com/Aefyr/SAI/releases/tag/4.1

![2](https://user-images.githubusercontent.com/47755037/90989554-1ba0ec00-e58a-11ea-99f6-509070b39480.png)
