### ISSUE TITLE
Missing "Used on" note when generating a random email from SL button

### ISSUE THREAD

**Issue by ajdor** [simple-login/browser-extension#58]
**Description:**
When using the SL button located right to email input forms in websites, the randomly generated email is missing the "Used on" note that can be found when accessing the extension menu or in the SL dashboard.

**Expected behavior:**
The generated email should have the "Used on" note to make it easier to find

**How to reproduce:**
- Go to any website where you can generate a random email using the SL Button next to input form (such as https://haveibeenpwned.com/)
- Click on the SL button next to the email input
- Check that the random email has been generated in the extension menu
- Notice that there is no indication/note on where the email was used
- Without reloading the page, click a second time on the SL button next to the email input
- Check the extension menu and notice that this time, the "Used on ..." note is created on the second email but not the first.
- Note that only the first (or couple of) email generated does not have the "Used on" note while every other one generated afterwards does.

**Note:** 
If you reload the webpage (F5 or Ctrl-F5), generating an email no longer has the "Used on" note , basically going back to step 1. 
Sometimes it takes 2 to 3 tries to see the "Used on" note.

**Tested on:** Firefox 80.0

**Comment by nguyenkims** [comment]
@ajdor thanks for reporting! I think @ngxson has fixed in this issue on the latest code that would be released in the next version, can you confirm @ngxson please?

**Comment by ajdor** [comment]
The issue is indeed fixed on the latest code (tested on 2.3.0.1).
I will leave a link to the commit for future reference : https://github.com/simple-login/browser-extension/commit/0d761cf2c3d3e00d4f896c2abb444aa035305abf
