### ISSUE TITLE
Suggestion: Provide a computer software (Linux, Windows & Mac)

### ISSUE THREAD

**Issue by ghost** [simple-login/browser-extension#6]
Some Internet Service Providers are very hostile against the idea behind SimpleLogin and other services that provide privacy and freedom to users.

As an example, accesing SimpleLogin's website is "illegal" at the University of Tokyo. According to the bureaucrats of the University, they have to control and record the activities of everyone and "SimpleLogin" falls in their firewall category of "anonymizer and proxies" ("illegal" to them).

Hence, if an ISP decides to block SimpleLogin website, a possible solution could be to provide a cross-platform software as the one provided by "ElectronMail" to access one's data on ProtonMail.

Even if there is no censorship by ISP providers a software for PC could be an important asset for the Company that would separate it from the rest. A computer application could provide access to SimpleLogin via TOR as "ElectronMail" does (unofficial desktop app for ProtonMail).

**Comment by ngxson** [comment]
Hi @ghost , for now I think it's quite difficult, because if they block simplelogin's website, that means they also block its API.

P/s: now I know why [ghost.org](https://ghost.org) can't name their github "Ghost"

**Comment by nguyenkims** [comment]
@ghost do you think we can try to convince the University of Tokyo to not block SimpleLogin? SimpleLogin is actually quite academia-friendly (free premium for students and reductions for professors/PHDs/...).
