### ISSUE TITLE
Horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by BeecherNetworks** [simple-login/browser-extension#7]
Sorry about all the issues, I hope I'm not being annoying!

There's a horizontal scrollbar in the SimpleLogin window in the Firefox extension, Windows 10 LTSC. As mentioned in another issues under the Android app, I'm running v3.1.1 so if that's responsible please feel free to close. Chrome is fine.

![image](https://user-images.githubusercontent.com/179583/84603936-5996db00-ae8a-11ea-8584-6def52fa6858.png)

**Comment by ngxson** [comment]
Hi @BeecherNetworks , do you have a long email in your list? If so, can you tell me if the "copy" button is also be shifted to the right side?

**Comment by BeecherNetworks** [comment]
The "shopping-cart-migration" one in the screenshot was the longest, there should be plenty of room, and it renders fine in Chrome. Here's another screenshot with no aliases at all:

![2020-06-17_23-53-37](https://user-images.githubusercontent.com/179583/84958787-0759f200-b0f6-11ea-9d36-4985a548de77.png)

**Comment by ngxson** [comment]
This issue will be fixed when my PR https://github.com/simple-login/browser-extension/pull/8 is merged. Firefox is so, so bad that it takes me many unnecessary steps to get into debug mode.

![image](https://user-images.githubusercontent.com/7702203/84961671-30ce4a00-b105-11ea-9607-422ccd467e13.png)

**Comment by BeecherNetworks** [comment]
Excellent, thanks! At least it's not owned by Google though, eh? :)

**Comment by nguyenkims** [comment]
@ngxson can you extract this fix to Firefox layout in a PR so it can be merged right away? The https://github.com/simple-login/browser-extension/pull/8 will probably take some times to review.

**Comment by ngxson** [comment]
@nguyenkims Sure, I'll just created https://github.com/simple-login/browser-extension/pull/9 which has only changes to css

**Comment by nguyenkims** [comment]
@BeecherNetworks it seems that the bug has been fixed on Firefox, should we close this issue?

**Comment by BeecherNetworks** [comment]
Yes thanks.
