### ISSUE TITLE
Changing shortcut keys in Chrome extension

### ISSUE THREAD

**Issue by timotree** [simple-login/browser-extension#96]
Is there a way to change the shortcut keys in the Chrome extension? I know Firefox allows it under "Manage Extension Shortcuts" but I can't find something similar in Chrome.

I use the default Ctrl+Shift+S for PowerToys Run and this extension is overriding it.

**Comment by nguyenkims** [comment]
@timotree You can change the shortcut here https://github.com/simple-login/browser-extension/blob/master/src/manifest.json#L40, rebuild the extension and install it into your browser.

**Comment by timotree** [comment]
What about for the casual end user? I could edit the manifest but I'm not familiar with rebuilding extensions and installing them from outside of the Web Store.

Wouldn't this method mess up auto-updates from the Web Store? I also prefer to load my extensions from there because I have several computers that I sync Chrome across, so this would presumably need to be done for all of them.

**Comment by nguyenkims** [comment]
I see, in this case maybe you can create a feature request on our forum at https://github.com/simple-login/app/discussions to be able to configure the shortcut.

**Comment by timotree** [comment]
Will do, thanks!
