### ISSUE TITLE
Allow for random charachters after website name

### ISSUE THREAD

**Issue by thibaultmol** [simple-login/browser-extension#99]
I don't think it's covered in https://github.com/simple-login/browser-extension/issues/95 but it's slightly relevant maybe.
Basically I want my alias's to be something like
github-az1r856ysr18y5j1ryj851zsry9j@mydomain.com 
So the extension would use the website name as a prefix and then put it's usually random strings after that. 
While I know it puts the website it was created on in the alias description.
I think having it in the actual alias makes it even more clear.

**Comment by nguyenkims** [comment]
@thibaultmol thanks for the idea!

**Comment by thibaultmol** [comment]
I just realized that this is basically the existing feature "Random Prefix Generation"
So I'll close this unless you think they're different features.
